-- D1 schema for subscription-manager.
-- Apply with: wrangler d1 execute hotstack-subscriptions-db --file=schema/subscriptions.sql

CREATE TABLE IF NOT EXISTS subscriptions (
  id            TEXT PRIMARY KEY,           -- uuid, generated by the worker
  customer_id   TEXT NOT NULL,
  tier          TEXT NOT NULL CHECK (tier IN ('starter', 'pro', 'enterprise')),
  status        TEXT NOT NULL CHECK (status IN ('active', 'past_due', 'canceled', 'trialing')) DEFAULT 'trialing',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  renewal_date  TEXT,
  canceled_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_customer ON subscriptions(customer_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
